// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xF0EC7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OpsContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_OpsContainer);
    lv_obj_set_width(ui_OpsContainer, lv_pct(90));
    lv_obj_set_height(ui_OpsContainer, lv_pct(20));
    lv_obj_set_x(ui_OpsContainer, lv_pct(0));
    lv_obj_set_y(ui_OpsContainer, lv_pct(16));
    lv_obj_set_align(ui_OpsContainer, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_OpsContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_OpsContainer, lv_color_hex(0xBC1212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_OpsContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_OpsContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlusButton = lv_btn_create(ui_OpsContainer);
    lv_obj_set_width(ui_PlusButton, lv_pct(10));
    lv_obj_set_height(ui_PlusButton, lv_pct(80));
    lv_obj_set_align(ui_PlusButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_PlusButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PlusButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PlusLabel = lv_label_create(ui_PlusButton);
    lv_obj_set_width(ui_PlusLabel, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_PlusLabel, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_PlusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PlusLabel, "+");
    lv_obj_set_style_text_font(ui_PlusLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinusButton = lv_btn_create(ui_OpsContainer);
    lv_obj_set_width(ui_MinusButton, lv_pct(10));
    lv_obj_set_height(ui_MinusButton, lv_pct(80));
    lv_obj_set_x(ui_MinusButton, lv_pct(17));
    lv_obj_set_y(ui_MinusButton, lv_pct(0));
    lv_obj_set_align(ui_MinusButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_MinusButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MinusButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MinusLabel = lv_label_create(ui_MinusButton);
    lv_obj_set_width(ui_MinusLabel, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_MinusLabel, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_MinusLabel, lv_pct(-6));
    lv_obj_set_y(ui_MinusLabel, lv_pct(0));
    lv_obj_set_align(ui_MinusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinusLabel, "-");
    lv_obj_set_style_text_font(ui_MinusLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DoubleButton = lv_btn_create(ui_OpsContainer);
    lv_obj_set_width(ui_DoubleButton, lv_pct(10));
    lv_obj_set_height(ui_DoubleButton, lv_pct(80));
    lv_obj_set_x(ui_DoubleButton, lv_pct(35));
    lv_obj_set_y(ui_DoubleButton, lv_pct(0));
    lv_obj_set_align(ui_DoubleButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DoubleButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DoubleButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DoubleLabel = lv_label_create(ui_DoubleButton);
    lv_obj_set_width(ui_DoubleLabel, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_DoubleLabel, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_DoubleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DoubleLabel, "X");
    lv_obj_set_style_text_font(ui_DoubleLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DivButton = lv_btn_create(ui_OpsContainer);
    lv_obj_set_width(ui_DivButton, lv_pct(10));
    lv_obj_set_height(ui_DivButton, lv_pct(80));
    lv_obj_set_x(ui_DivButton, lv_pct(53));
    lv_obj_set_y(ui_DivButton, lv_pct(0));
    lv_obj_set_align(ui_DivButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DivButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DivButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DivLabel = lv_label_create(ui_DivButton);
    lv_obj_set_width(ui_DivLabel, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_DivLabel, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_DivLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DivLabel, ":");
    lv_obj_set_style_text_font(ui_DivLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Plus10Button = lv_btn_create(ui_OpsContainer);
    lv_obj_set_width(ui_Plus10Button, lv_pct(10));
    lv_obj_set_height(ui_Plus10Button, lv_pct(80));
    lv_obj_set_x(ui_Plus10Button, lv_pct(69));
    lv_obj_set_y(ui_Plus10Button, lv_pct(0));
    lv_obj_set_align(ui_Plus10Button, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Plus10Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Plus10Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Plus10Label = lv_label_create(ui_Plus10Button);
    lv_obj_set_width(ui_Plus10Label, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Plus10Label, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Plus10Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Plus10Label, "+10");
    lv_obj_set_style_text_font(ui_Plus10Label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Minus10Button = lv_btn_create(ui_OpsContainer);
    lv_obj_set_width(ui_Minus10Button, lv_pct(10));
    lv_obj_set_height(ui_Minus10Button, lv_pct(80));
    lv_obj_set_x(ui_Minus10Button, lv_pct(87));
    lv_obj_set_y(ui_Minus10Button, lv_pct(0));
    lv_obj_set_align(ui_Minus10Button, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Minus10Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Minus10Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Minus10Label = lv_label_create(ui_Minus10Button);
    lv_obj_set_width(ui_Minus10Label, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Minus10Label, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Minus10Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Minus10Label, "-10");
    lv_obj_set_style_text_font(ui_Minus10Label, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AnswerContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_AnswerContainer);
    lv_obj_set_width(ui_AnswerContainer, lv_pct(90));
    lv_obj_set_height(ui_AnswerContainer, lv_pct(20));
    lv_obj_set_align(ui_AnswerContainer, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_AnswerContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Answer1Button = lv_btn_create(ui_AnswerContainer);
    lv_obj_set_width(ui_Answer1Button, lv_pct(20));
    lv_obj_set_height(ui_Answer1Button, lv_pct(70));
    lv_obj_set_x(ui_Answer1Button, lv_pct(3));
    lv_obj_set_y(ui_Answer1Button, lv_pct(0));
    lv_obj_add_flag(ui_Answer1Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Answer1Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Answer1Label = lv_label_create(ui_Answer1Button);
    lv_obj_set_width(ui_Answer1Label, lv_pct(100));
    lv_obj_set_height(ui_Answer1Label, lv_pct(100));
    lv_obj_set_align(ui_Answer1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Answer1Label, "");

    ui_Answer2Button = lv_btn_create(ui_AnswerContainer);
    lv_obj_set_width(ui_Answer2Button, lv_pct(20));
    lv_obj_set_height(ui_Answer2Button, lv_pct(70));
    lv_obj_set_x(ui_Answer2Button, lv_pct(27));
    lv_obj_set_y(ui_Answer2Button, lv_pct(0));
    lv_obj_add_flag(ui_Answer2Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Answer2Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Answer2Label = lv_label_create(ui_Answer2Button);
    lv_obj_set_width(ui_Answer2Label, lv_pct(100));
    lv_obj_set_height(ui_Answer2Label, lv_pct(100));
    lv_obj_set_align(ui_Answer2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Answer2Label, "");

    ui_Answer3Button = lv_btn_create(ui_AnswerContainer);
    lv_obj_set_width(ui_Answer3Button, lv_pct(20));
    lv_obj_set_height(ui_Answer3Button, lv_pct(70));
    lv_obj_set_x(ui_Answer3Button, lv_pct(52));
    lv_obj_set_y(ui_Answer3Button, lv_pct(0));
    lv_obj_add_flag(ui_Answer3Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Answer3Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Answer3Label = lv_label_create(ui_Answer3Button);
    lv_obj_set_width(ui_Answer3Label, lv_pct(100));
    lv_obj_set_height(ui_Answer3Label, lv_pct(100));
    lv_obj_set_align(ui_Answer3Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Answer3Label, "");

    ui_Answer4Button = lv_btn_create(ui_AnswerContainer);
    lv_obj_set_width(ui_Answer4Button, lv_pct(20));
    lv_obj_set_height(ui_Answer4Button, lv_pct(70));
    lv_obj_set_x(ui_Answer4Button, lv_pct(77));
    lv_obj_set_y(ui_Answer4Button, lv_pct(0));
    lv_obj_add_flag(ui_Answer4Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Answer4Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Answer4Label = lv_label_create(ui_Answer4Button);
    lv_obj_set_width(ui_Answer4Label, lv_pct(100));
    lv_obj_set_height(ui_Answer4Label, lv_pct(100));
    lv_obj_set_align(ui_Answer4Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Answer4Label, "");

    ui_ExerciseLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ExerciseLabel, lv_pct(70));
    lv_obj_set_height(ui_ExerciseLabel, lv_pct(15));
    lv_obj_set_align(ui_ExerciseLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ExerciseLabel, "");
    lv_obj_set_style_text_align(ui_ExerciseLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ExerciseLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ExerciseLabel, lv_color_hex(0xCFDE19), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ExerciseLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ExerciseLabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResultLable = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ResultLable, lv_pct(40));
    lv_obj_set_height(ui_ResultLable, lv_pct(16));
    lv_obj_set_x(ui_ResultLable, lv_pct(0));
    lv_obj_set_y(ui_ResultLable, lv_pct(20));
    lv_obj_set_align(ui_ResultLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResultLable, "");
    lv_obj_set_style_text_color(ui_ResultLable, lv_color_hex(0x3023DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResultLable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ResultLable, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResultLable, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ResultLable, lv_color_hex(0x1D900B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ResultLable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ResultLable, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScoreLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ScoreLabel, lv_pct(20));
    lv_obj_set_height(ui_ScoreLabel, lv_pct(12));
    lv_label_set_text(ui_ScoreLabel, "0");
    lv_obj_set_style_text_color(ui_ScoreLabel, lv_color_hex(0x471BF9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScoreLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ScoreLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ScoreLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ScoreLabel, lv_color_hex(0x7514D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ScoreLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ScoreLabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
